### ISSUE TITLE
Update uniloc dependency to use 0.3.0

### ISSUE THREAD

**Issue by seriouscircus** [bkonkle/unirouter#6]
uniloc has been updated and allows now case-sensitive urls (thanks for this!). Would be great to have unirouter use this updated version.

**Comment by KnisterPeter** [comment]
Please merge this and release a new version.

**Comment by bkonkle** [comment]
I'd love to, but My family and I are in the middle of a big move and I'm
devoting all my attention to catching up and keeping my head above water.
I'll be happy to merge as soon as I can. Thanks!

**Comment by bkonkle** [comment]
Finally got this updated. Sorry it took me so long! Thanks for letting me know about the uniloc update, @seriouscircus!

**Comment by seriouscircus** [comment]
Great! Thanks!
